[meta]
name = "ShellExecutor-MCDR"
author = [{ "github" = "Mooling0602" }]
maintainers = []
description = "Quickly execute shell commands in MCDR console or in the game."
main-branch = "main"
license = "GPL-3.0"

[platform]
remote-hoster = [{ "github" = "https://github.com" }]
